import { Octokit } from '@octokit/rest';
import { formatMarkdown } from './markdown.js';
import { ConsensusPlan } from '../consensus/types.js';

export async function postToGitHub(
  plan: ConsensusPlan,
  owner: string,
  repo: string,
  issueNumber: number,
  token: string,
  verbose: boolean = false
): Promise<void> {
  const octokit = new Octokit({ auth: token });

  const markdown = formatMarkdown(plan, verbose);
  const comment = `${markdown}\n\n---\n*Generated by [Plan Council](https://github.com/mstroeck/pcl)*`;

  await octokit.issues.createComment({
    owner,
    repo,
    issue_number: issueNumber,
    body: comment,
  });
}
